name: Draw Keymap
on:
  workflow_dispatch: # allows manual run
  push:
    paths:
      - "config/*.keymap"
      - "config/*.conf"

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Keymap Drawer
        run: pip install keymap-drawer

      - name: Parse and Draw
        run: |
          mkdir -p keymap-drawer
          keymap parse -z config/corne.keymap > keymap-drawer/corne.yaml
          keymap draw keymap-drawer/corne.yaml > keymap-drawer/corne.svg

      - name: Commit updated images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update keymap drawer images"
          file_pattern: "keymap-drawer/*.svg keymap-drawer/*.yaml"
